name: Build and Test

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  workflow_call:
  workflow_dispatch:

jobs:

  linux:
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        runner: [ ubuntu-24.04, ubuntu-24.04-arm ]

    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ github.worksapce }}

      - if: ${{ !contains(matrix.runner, 'arm') }}
        uses: seanmiddleditch/gha-setup-ninja@v5

      - if: contains(matrix.runner, 'arm')
        uses: seanmiddleditch/gha-setup-ninja@v5
        with:
          # TODO(andrurogerz): seanmiddleditch/gha-setup-ninja does not properly
          # detect Linux on arm64 and always installs the x86_64 ninja package.
          # For now, we can fix this by overriding the platform string to force
          # the downloading the proper package. We also require a newer ninja
          # version since aarch64 packages were not released until v1.12.0 and
          # the default gha-setup-ninja installs is v1.11.1.
          platform: linux-aarch64
          version: 1.12.1 # latest sccache version

      - name: Configure
        run: |
          cmake -B ${{ github.workspace }}/build    \
                -S ${{ github.workspace }}          \
                -G Ninja

      - name: Build
        run: |
          cmake --build ${{ github.workspace }}/build

      - name: Test
        run: |
          ctest --test-dir ${{ github.workspace}}/build   \
                --output-on-failure                       \
                --progress                                \
                --verbose
